# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'client_side/gui/client.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_client_window(object):
    def setupUi(self, client_window):
        client_window.setObjectName("client_window")
        client_window.setFixedSize(800, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(client_window.sizePolicy().hasHeightForWidth())
        client_window.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(client_window)
        self.centralwidget.setObjectName("centralwidget")
        self.contacts_listView = QtWidgets.QListView(self.centralwidget)
        self.contacts_listView.setGeometry(QtCore.QRect(10, 50, 200, 390))
        self.contacts_listView.setObjectName("contacts_listView")
        self.private_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.private_lineEdit.setEnabled(False)
        self.private_lineEdit.setGeometry(QtCore.QRect(10, 540, 200, 20))
        self.private_lineEdit.setObjectName("private_lineEdit")
        self.contacts_add_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.contacts_add_pushButton.setGeometry(QtCore.QRect(10, 30, 200, 20))
        self.contacts_add_pushButton.setStyleSheet("background-color: rgb(170, 255, 0);")
        self.contacts_add_pushButton.setObjectName("contacts_add_pushButton")
        self.contacts_remove_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.contacts_remove_pushButton.setGeometry(QtCore.QRect(10, 440, 200, 20))
        self.contacts_remove_pushButton.setStyleSheet("background-color: rgb(255, 85, 0);")
        self.contacts_remove_pushButton.setObjectName("contacts_remove_pushButton")
        self.private_label = QtWidgets.QLabel(self.centralwidget)
        self.private_label.setGeometry(QtCore.QRect(10, 520, 200, 16))
        self.private_label.setObjectName("private_label")
        self.message_plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.message_plainTextEdit.setGeometry(QtCore.QRect(220, 500, 570, 90))
        self.message_plainTextEdit.setObjectName("message_plainTextEdit")
        self.message_label = QtWidgets.QLabel(self.centralwidget)
        self.message_label.setGeometry(QtCore.QRect(220, 480, 570, 15))
        self.message_label.setObjectName("message_label")
        self.chat_plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.chat_plainTextEdit.setEnabled(False)
        self.chat_plainTextEdit.setGeometry(QtCore.QRect(220, 30, 570, 430))
        self.chat_plainTextEdit.setObjectName("chat_plainTextEdit")
        self.contacts_label = QtWidgets.QLabel(self.centralwidget)
        self.contacts_label.setGeometry(QtCore.QRect(10, 10, 200, 15))
        self.contacts_label.setObjectName("contacts_label")
        self.message_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.message_pushButton.setGeometry(QtCore.QRect(10, 570, 200, 20))
        self.message_pushButton.setStyleSheet("background-color: rgb(170, 255, 0);")
        self.message_pushButton.setObjectName("message_pushButton")
        self.chat_label = QtWidgets.QLabel(self.centralwidget)
        self.chat_label.setGeometry(QtCore.QRect(220, 10, 570, 15))
        self.chat_label.setObjectName("chat_label")
        client_window.setCentralWidget(self.centralwidget)

        self.retranslateUi(client_window)
        QtCore.QMetaObject.connectSlotsByName(client_window)

    def retranslateUi(self, client_window):
        _translate = QtCore.QCoreApplication.translate
        client_window.setWindowTitle(_translate("client_window", "Chat Client"))
        self.contacts_add_pushButton.setText(_translate("client_window", "Add new contact"))
        self.contacts_remove_pushButton.setText(_translate("client_window", "Remove selected contact"))
        self.private_label.setText(_translate("client_window", "Private to user:"))
        self.message_label.setText(_translate("client_window", "Message text:"))
        self.contacts_label.setText(_translate("client_window", "Contact list"))
        self.message_pushButton.setText(_translate("client_window", "Send message"))
        self.chat_label.setText(_translate("client_window", "Chat window"))
